# Commands

## ls
- -a --all包括隐藏文件
- -l 详细信息(long)
- -h size数据人类可读
- -i inode值
- -d 目录信息

----
-rw-r-----
----
首字符 `-` 表示文件； `d` 表示目录； `l` 表示软链接

分别对应 `user`,`group`,`other` 的权限

## mkdir

- -p --parents 递归创建

## cp

----
cp [option] file1 file2 desddir
----

- -r 对目录下面的内容递归操作
- -p --preserve 保留指定的属性（模式，所有权，时间戳）

NOTE: 可以操作多个路径，也可以改名

## 文件操作

- touch
- cat [-n] 显示行号
- more/less
- head [-n]
- tail [-nf]

## ln

----
ln -s /etc/services /tmp/services.soft
ln /etc/services /tmp/services.hard
----

## chmod

针对文件

- `r 4 cat/more/less/head/tail`
- `w 2 vim`
- `x 1 script command`

针对目录

- `r 4 ls`
- `w 2 touch/mkdir/rm`
- `x 1 cd`

----
chmod 777 somefile
chmod 777 somedir
chmod -R 777 somedir
----

`[-R]` 递归改变子文件夹及子文件的权限


## chown/chgrp

----
chown yyy somedir
chgrp [group] somedir
----

NOTE: 只有管理员才有 `chown` 的权限


## find

1. 根据文件名称搜索
+
----
find /etc -name init     //精确搜索
find /etc -name *init*   //通配符
find /etc -iname init    //忽略大小写
----

2. 根据文件大小搜索 +
size需要换算成数据块：1数据块=0.5k +
100M = 100*1024＊2 = 204800
+
----
find -size +204800   //大于100M
find -size -204800   //小于100M
----

3. 根据用户查找
+
----
find /home -user yyy
find /home -group yyy
----

4. 根据时间属性查找
+
----
find /etc -amin -5    //访问时间access 5分钟
find /etc -cmin -5    //文件属性change 5分钟
find /etc -mmin -5    //文件内容modify 5分钟
----

5. 根据文件类型查找
+
----
find /etc -type f    // f文件
find /etc -type d    // d目录
find /etc -type l    // l软链接
----

6. 逻辑查找
+
`-a` 表示and，`-o` 表示or
+
----
//查找大于80M小于100M的文件
find /etc -size +163840 -a -size -204800
----

## locate

----
locate inittab
locate -i inittab   //不区分大小写
----

手动更新文件资料库
----
updatedb
----
NOTE: loacte资料库不包含 `/tmp` 正面的文件

## grep

文件内容查找 +
`-i` 不区分大小写 +
`-v` 排除指定字符串
----
grep mysql /root/install.log
grep -v ^# /etc/inittab        //删除#号开头的行
----

## man

命令查看帮助信息

----
man ls
man services   //查看配置文件的帮助信息，不需要绝对路径
----

shell内置命令要使用`help`

----
help cd
----


## 用户管理

----
useradd yyy
passwd yyy     //设置更改密码
who            //用户登录信息
w              //详细的登录信息
----

## 压缩/解压缩

- gzip *只能压缩文件*，不能压缩目录, 不保留原文件
+
----
gzip file
gunzip file.gz    //或者 gzip -d file.gz
----
- tar
+
* -c 打包
* -v 详细信息
* -f 指定文件名
* -z 解压缩
+
----
tar -zcvf Japan.tar.gz Japan   //打包
tar -zxvf Japan.tar.gz         //解包
----
- zip 会保留原文件
+
----
zip [-r] file.zip file/directory
unzip file.zip
----
- bzip2 压缩比会非常高
+
* -k 保留原文件
+
----
bzip2 -k dir                    //打包
tar -cjf Japan.tar.bz2 Japan    //打包
tar -xjf Japan.tar.bz2          //解包
----


## 网络命令

- ping
+
* -c 发送次数
+
----
ping -c 5 192.168.0.1
----
- last 用户登录重启信息
- lastlog 列出所有用户最后的登录时间
- traceroute
+
----
traceroute www.baidu.com
----
- netstat
* -t TCP协议
* -u UDP协议
* -l 监听
* -r 路由
* -n 显示IP地址和端口号
+
----
netstat -tlun
netstat -an     //所有的端口，还可以显示正在连接的
netstat -rn     //显示本机路由表
----

## shutdown

* -h 关机
* -c 取消前一个关机命令
* -r 重启
----
shutdown -h now        //关机
shutdown -h 20:30      //定时关机

shutdown -r now        //重启
reboot

logout                 //退出登录
----

## Vim

vim配置文件: `~/.vimrc`

.进入编辑模式
- `a`  在光标所在字符后插入
- `A`  在光标所在行尾插入
- `i`  在光标所在字符前插入
- `I`  在光标所在行首插入
- `o`  在光标下插入新行
- `O`  在光标上插入新行

.定位命令
- `:set nu`    设置行号
- `:set nonu`  取消行号
- `:gg`  到第一行
- `:G`   到最后一行
- `:nG`  到第n行
- `:n`   到第n行
- `$`    移动到行尾
- `0`    移动到行首

.删除命令
- `x`        删除光标所在处字符
- `nx`       删除光标所在处后n个字符
- `dd`       删除光标所在行
- `ndd`      删除n行
- `dG`       删除光标所在行到文件末尾的内容
- `D`        删除光标所在处到行尾的内容
- `:n1,n2d`  删除指定范围的行

.复制粘贴命令
- `yy`       复制当前行
- `nyy`      复制当前行以下n行
- `dd`       剪切当前行
- `ndd`      剪切当前行以下n行
- `p`        粘贴在当前光标所在行下
- `P`        粘贴在当前光标所在行上

.替换和取消命令
- `r`        取代光标所在处字符
- `R`        从光标的在处开始替换字符，ESC结束
- `u`        取消上一步操作


## 软件包管理

.rpm安装
- `rpm -i` 安装
- `rpm -U` 升级
- `rpm -e` 缷载
- `rpm -q` 查询
- `rpm -qa` 查询所有已经安装的包
+
----
rpm -qa | grep httpd
----
- `rpm -qi` 查询已安装包的信息
- `rpm -qip` 查询未安装包的信息（接全名）
- `rpm -ql` 查询包文件安装的位置
- `rpm -qf` 查询系统文件所属的包名
- `rpm -qR` 查询包的依赖性
- `rpm -V` RMP包的校验（是否被修改过）
- `dpkg -i`

.yum
- `yum list`
- `yum search [包名]`
- `yum -y install [包名]`
- `yum -y update [包名]`
- `yum -y remove [包名]`

.源码安装
- 源代码保存位置：`/usr/local/src/`
- 软件安装位置： `/usr/local/`


.rpm包启动
----
/etc/rc.d/init.d/[httpd] start
service [httpd] start
----

.源码包启动
----
/usr/local/apache2/bin/apachectl start    //只能用路径启动
----

.su切换用户
----
su - [userA]      // 中间的 - 不能省略
----